name: Run bgmi Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/0 * * * *'

jobs:
  run_bgmi_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: binary by @ROYxOWNER
        run: chmod +x bgmi
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install required packages
        run: |
          pip install telebot pymongo aiohttp

      - name: Run m.py
        run: python3 m.py
